version: '3.8'

services:
  t212-bot:
    build: .
    container_name: t212-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Rome
